export const HTTPCookies = {
  token: "accessToken",
  userID: "userId",
  userName: "userName",
  userNameArabic: "userNameArabic",
  email: "userEmail",
  appTypeId: "appTypeId",
  otpVerified: "otpVerified",
  otpValidationStatus: "otpValidationStatus",
  appTypes: "appTypes",
  tenancyId: "tenancyId",
  tenantId: "tenantId",
  tenantName: "tenantName",
  otpReferenece: "otpReference",
  refreshToken: "refreshToken",
};
