// Query constants used in queries and mutations
export enum QueryCosntant {
  USERS = "users",
  USER = "user",
  GROUPS = "groups",
  USER_Details = "user_details",
  SEARCH_USER = "search_user",
  PARTY_CODES = "party_codes",
  ROLES = "roles",
  GROUP_USERS = "group_users",
  PARTIES = "parties",
  SITES = "locations",
  SITEDetails = "location",
  PARTY_DETAILS = "party_details",
  BUSINESS_RULE = "business_rule",
  PRODUCTS = "products",
  EventGroups = "event-groups",
  EVENTS = "events",
  CHANNELS_DATA = "channels_data",
  LOOKUP_PARAMETERS = "lookup_parameters",
  CHANNELS = "channels",
  MESSAGES = "messages",
  MESSAGES_ID = "messages_id",
  MESSAGE_STATUS_LOGS = "message_status_logs",
  EVENT_GROUPS = "event_groups",
  EVENT_GROUPS_BY_ID = "event_groups_by_id",
  SYSTEM = "system",
  TENANTS = "tenants",
  TENANT = "tenant",
  CUSTOMER = "customer",
  CUSTOMERS = "customers",
  SENDERS = "senders",
  WHATSAPP_TEMPLATES = "whatsapp_templates",
  WHATSAPP_TEMPLATE_ID = "whatsapp_template_id",
}
